CREATE TABLE  BOOK 
   (	ISBN NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	AUTHOR VARCHAR2(255), 
	PRICE NUMBER, 
	TYPE VARCHAR2(255) NOT NULL ENABLE, 
	NUMBEROFPAGES NUMBER, 
	QUANTITY NUMBER, 
	COPYLEFT NUMBER NOT NULL ENABLE, 
	 CONSTRAINT BOOK_PK PRIMARY KEY (ISBN) ENABLE
   ) ;

CREATE TABLE  BORROW 
   (	ISBN NUMBER, 
	LECTUREID NUMBER, 
	BORROWDATE VARCHAR2(255), 
	RETURNDATE VARCHAR2(255)
   ) ;

   CREATE TABLE  LECTURE
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(255) NOT NULL ENABLE, 
	AGE NUMBER, 
	SEX VARCHAR2(100), 
	DEPARTMENT VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT LECTURE_PK PRIMARY KEY (ID) ENABLE
   ) ;

   CREATE TABLE  admin 
   (	username VARCHAR2(255) NOT NULL ENABLE, 
	password VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT admin_PK PRIMARY KEY (username) ENABLE
   ) ;