/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookStore;

import javax.swing.JFrame;

/**
 *
 * @author Nahom
 */
public class BookEditor extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public BookEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBookPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newTitle = new javax.swing.JTextField();
        newISBN = new javax.swing.JTextField();
        newAuthor = new javax.swing.JTextField();
        newQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createBook = new javax.swing.JButton();
        editBook1 = new javax.swing.JPanel();
        defaultTitle = new javax.swing.JComboBox<>();
        updateBook = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editAuthor = new javax.swing.JTextField();
        editQuantity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        editTitle = new javax.swing.JTextField();
        isbnList = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        editPage = new javax.swing.JTextField();
        editPrice = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newType = new javax.swing.JTextField();
        newPrice = new javax.swing.JTextField();
        newPage = new javax.swing.JTextField();
        pLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newLecturePannel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        newBookPanel.setBackground(new java.awt.Color(255, 51, 102));
        newBookPanel.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Book Title:");
        newBookPanel.add(jLabel1);
        jLabel1.setBounds(10, 60, 90, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("ISBN:");
        newBookPanel.add(jLabel2);
        jLabel2.setBounds(30, 90, 60, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Author:");
        newBookPanel.add(jLabel3);
        jLabel3.setBounds(20, 110, 60, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Quantity:");
        newBookPanel.add(jLabel4);
        jLabel4.setBounds(10, 140, 50, 40);
        newBookPanel.add(newTitle);
        newTitle.setBounds(70, 60, 130, 20);
        newBookPanel.add(newISBN);
        newISBN.setBounds(70, 90, 130, 20);
        newBookPanel.add(newAuthor);
        newAuthor.setBounds(70, 120, 130, 20);
        newBookPanel.add(newQuantity);
        newQuantity.setBounds(70, 150, 130, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Type:");
        newBookPanel.add(jLabel5);
        jLabel5.setBounds(10, 180, 40, 30);

        createBook.setText("Create");
        createBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBookMouseClicked(evt);
            }
        });
        newBookPanel.add(createBook);
        createBook.setBounds(70, 290, 130, 23);

        editBook1.setBackground(new java.awt.Color(102, 102, 255));
        editBook1.setLayout(null);

        String[] title2=bookStore.BookStore.getGenre();
        defaultTitle.setModel(new javax.swing.DefaultComboBoxModel<>(title2));
        defaultTitle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                defaultTitleItemStateChanged(evt);
            }
        });
        defaultTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaultTitleMouseClicked(evt);
            }
        });
        editBook1.add(defaultTitle);
        defaultTitle.setBounds(70, 10, 170, 30);

        updateBook.setText("Update");
        updateBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBookMouseClicked(evt);
            }
        });
        editBook1.add(updateBook);
        updateBook.setBounds(20, 310, 240, 50);

        jLabel11.setText("Type:");
        editBook1.add(jLabel11);
        jLabel11.setBounds(20, 10, 40, 30);

        jLabel12.setText("Quantity:");
        editBook1.add(jLabel12);
        jLabel12.setBounds(10, 140, 50, 40);

        jLabel13.setText("Author:");
        editBook1.add(jLabel13);
        jLabel13.setBounds(20, 110, 60, 40);

        editAuthor.setText("author");
        editBook1.add(editAuthor);
        editAuthor.setBounds(70, 120, 170, 30);
        editBook1.add(editQuantity);
        editQuantity.setBounds(70, 150, 70, 30);

        jLabel14.setText("ISBN:");
        editBook1.add(jLabel14);
        jLabel14.setBounds(20, 40, 60, 30);

        jLabel15.setText("Book Title:");
        editBook1.add(jLabel15);
        jLabel15.setBounds(10, 80, 90, 30);
        editBook1.add(editTitle);
        editTitle.setBounds(70, 80, 170, 30);

        isbnList.setModel(new javax.swing.DefaultComboBoxModel<>(bookStore.BookStore.getBookListById()));
        isbnList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isbnListItemStateChanged(evt);
            }
        });
        editBook1.add(isbnList);
        isbnList.setBounds(70, 40, 170, 30);

        jLabel22.setText("Pages:");
        editBook1.add(jLabel22);
        jLabel22.setBounds(10, 190, 40, 14);
        editBook1.add(editPage);
        editPage.setBounds(70, 190, 60, 20);
        editBook1.add(editPrice);
        editPrice.setBounds(70, 220, 70, 30);

        jLabel23.setText("Price:");
        editBook1.add(jLabel23);
        jLabel23.setBounds(10, 230, 40, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter some text here...\n");
        jScrollPane1.setViewportView(jTextArea1);

        editBook1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 40, 260, 240);

        jLabel26.setText("Book Conetents");
        editBook1.add(jLabel26);
        jLabel26.setBounds(300, 10, 140, 30);

        jButton2.setText("Delete");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        editBook1.add(jButton2);
        jButton2.setBounds(20, 370, 240, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/west-bookstore-2-770x260.jpg"))); // NOI18N
        editBook1.add(jLabel6);
        jLabel6.setBounds(0, 200, 510, 270);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/images (2).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        editBook1.add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 210);

        newBookPanel.add(editBook1);
        editBook1.setBounds(290, 20, 510, 580);
        editBook1.setVisible(true);
        newBookPanel.add(newType);
        newType.setBounds(70, 190, 130, 20);

        String prices=String.valueOf(bookStore.BookStore.getPriceById((String)isbnList.getSelectedItem()));
        editPrice.setText(prices);
        newBookPanel.add(newPrice);
        newPrice.setBounds(70, 250, 130, 20);

        String pages=String.valueOf(bookStore.BookStore.getNumberOfPagesById((String)isbnList.getSelectedItem()));
        editPage.setText(pages);
        newBookPanel.add(newPage);
        newPage.setBounds(70, 220, 130, 20);

        pLabel.setForeground(new java.awt.Color(255, 255, 51));
        pLabel.setText("Pages:");
        newBookPanel.add(pLabel);
        pLabel.setBounds(10, 220, 40, 14);

        rLabel.setForeground(new java.awt.Color(255, 255, 51));
        rLabel.setText("Price:");
        newBookPanel.add(rLabel);
        rLabel.setBounds(10, 250, 40, 14);

        result.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newBookPanel.add(result);
        result.setBounds(20, 340, 250, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/026.jpg"))); // NOI18N
        newBookPanel.add(jLabel8);
        jLabel8.setBounds(0, 20, 290, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/images (1).jpg"))); // NOI18N
        newBookPanel.add(jLabel9);
        jLabel9.setBounds(0, 210, 290, 190);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/images (3).jpg"))); // NOI18N
        newBookPanel.add(jLabel10);
        jLabel10.setBounds(0, 390, 290, 80);

        getContentPane().add(newBookPanel, "card2");

        jButton1.setText("Welcome 2");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout newLecturePannelLayout = new javax.swing.GroupLayout(newLecturePannel);
        newLecturePannel.setLayout(newLecturePannelLayout);
        newLecturePannelLayout.setHorizontalGroup(
            newLecturePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newLecturePannelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton1)
                .addContainerGap(566, Short.MAX_VALUE))
        );
        newLecturePannelLayout.setVerticalGroup(
            newLecturePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newLecturePannelLayout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(81, 81, 81))
        );

        getContentPane().add(newLecturePannel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        newBookPanel.setVisible(true);
        newLecturePannel.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void createBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBookMouseClicked
        String title=newTitle.getText();
        int isbn=Integer.parseInt(newISBN.getText());
        String author=newAuthor.getText();
        int quantity=Integer.parseInt(newQuantity.getText());
        String genre=newType.getText();
        int price=Integer.parseInt(newPrice.getText());
        int numberOfPages=Integer.parseInt(newPage.getText());
        int copyLeft=quantity;
        String query="insert into book values('"+isbn+"','"+title+"','"+author+"','"+price+"','"+genre+"','"+numberOfPages+"','"+quantity+"','"+copyLeft+"')";
        BookStore.excuteUpdate(query);
        this.setVisible(false);
        BookEditor edit=new BookEditor();
        edit.setTitle("Book Editor");
        edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        edit.setVisible(true);
        edit.result.setText("Sucessfully Added 1 book");
    }//GEN-LAST:event_createBookMouseClicked

    private void updateBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBookMouseClicked
        int id=Integer.parseInt((String)isbnList.getSelectedItem());
        String title=editTitle.getText();
        String author=editAuthor.getText();
        String type=newType.getText();
        int price=Integer.parseInt(editPrice.getText());
        int quantity=Integer.parseInt(editQuantity.getText());
        int pages=Integer.parseInt(editPage.getText());
        String query="update book set title='"+title+"', author=' "+author+"', Numberofpages='"+pages+"', price='"+price+"', quantity='"+quantity+"', type='"+type+"' where isbn='"+id+"'";
        BookStore.excuteUpdate(query);
        this.setVisible(false);
BookEditor edit=new BookEditor();
        edit.setTitle("Book Editor");
        edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        edit.setVisible(true);
        edit.result.setText("Sucessfully Updated "+title+" book");
    }//GEN-LAST:event_updateBookMouseClicked

    private void isbnListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isbnListItemStateChanged
            String isbn=(String)isbnList.getSelectedItem();
            String id2=BookStore.getTitleById(isbn);
            editTitle.setText(id2);
            String author=BookStore.getAuthorById(isbn);
            editAuthor.setText(author);
            int quantity=BookStore.getQuantityById(isbn);
            editQuantity.setText(String.valueOf(quantity));
            String pages2=String.valueOf(BookStore.getNumberOfPagesById(isbn));
            editPage.setText(pages2);
            String prices2=String.valueOf(BookStore.getPriceById(isbn));
            editPrice.setText(prices2);
            String type2=BookStore.getTypeById(isbn);
            
    }//GEN-LAST:event_isbnListItemStateChanged

    private void defaultTitleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_defaultTitleItemStateChanged
        String type=(String)defaultTitle.getSelectedItem();
        isbnList.setModel(new javax.swing.DefaultComboBoxModel<>(BookStore.getListByType(type)));
    }//GEN-LAST:event_defaultTitleItemStateChanged

    private void defaultTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultTitleMouseClicked
                    
        try{   
        int i=0;
            
            while(i<defaultTitle.getItemCount()+1){
            String current=defaultTitle.getItemAt(i);
            String next=defaultTitle.getItemAt(i+1);
            if (current.compareToIgnoreCase(next)==0){
              defaultTitle.removeItemAt(i+1);
            }
            i++;
            }}
            catch(Exception e){
                     
          }
    }//GEN-LAST:event_defaultTitleMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int id=Integer.parseInt((String)isbnList.getSelectedItem());
        String query="delete from book where isbn='"+id+"'";
        BookStore.excuteUpdate(query);
                this.setVisible(false);
        BookEditor edit=new BookEditor();
        edit.setTitle("Book Editor");
        edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        edit.setVisible(true);
        edit.result.setText("Sucessfully Deleted 1 book");        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBook;
    private javax.swing.JComboBox<String> defaultTitle;
    private javax.swing.JTextField editAuthor;
    private javax.swing.JPanel editBook1;
    private javax.swing.JTextField editPage;
    private javax.swing.JTextField editPrice;
    private javax.swing.JTextField editQuantity;
    private javax.swing.JTextField editTitle;
    private javax.swing.JComboBox<String> isbnList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField newAuthor;
    private javax.swing.JPanel newBookPanel;
    private javax.swing.JTextField newISBN;
    private javax.swing.JPanel newLecturePannel;
    private javax.swing.JTextField newPage;
    private javax.swing.JTextField newPrice;
    private javax.swing.JTextField newQuantity;
    private javax.swing.JTextField newTitle;
    private javax.swing.JTextField newType;
    private javax.swing.JLabel pLabel;
    private javax.swing.JLabel rLabel;
    private javax.swing.JLabel result;
    private javax.swing.JButton updateBook;
    // End of variables declaration//GEN-END:variables
}
