/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookStore;

import javax.swing.JFrame;

/**
 *
 * @author Nahom
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        result = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addBookButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idList = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        month = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 640));
        getContentPane().setLayout(null);

        String[][] list=bookStore.BookStore.getBookDetails();
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            list,
            new String [] {
                "ISBN", "Title", "Author", "Price","Quantity","Max Pages"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 750, 240);
        getContentPane().add(result);
        result.setBounds(350, 490, 130, 0);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(null);

        addBookButton.setText("Add Book");
        addBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookButtonMouseClicked(evt);
            }
        });
        jPanel1.add(addBookButton);
        addBookButton.setBounds(440, 533, 190, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Book Store");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 320, 140, 40);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select book By ID:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 400, 90, 20);

        String list4[]=bookStore.BookStore.getBookListById();
        String clist[]=new String[20];
        for(int i=0,j=0;list4[i]!=null;i++){
            if(!list4[i].isEmpty() && bookStore.BookStore.hasCopies(list4[i])){
                clist[j]=list4[i];
                j++;
            }
        }
        idList.setModel(new javax.swing.DefaultComboBoxModel<>(clist));
        idList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idListItemStateChanged(evt);
            }
        });
        idList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idListMouseClicked(evt);
            }
        });
        jPanel1.add(idList);
        idList.setBounds(130, 400, 70, 20);

        String id=(String)idList.getSelectedItem();
        String title=bookStore.BookStore.getTitleById(id);
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(title);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 400, 180, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 450, 80, 30);
        jPanel1.add(date);
        date.setBounds(80, 450, 80, 30);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April","May","JUNE","July","August","September","Octorber","November","December" }));
        jPanel1.add(month);
        month.setBounds(240, 450, 100, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Month:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(180, 460, 40, 14);

        year.setText("2016");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year);
        year.setBounds(400, 450, 100, 30);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Year:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(370, 460, 30, 20);

        submit.setText("Buy");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(210, 530, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/images (3).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(14, 324, 340, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/images.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(344, 324, 390, 250);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/west-bookstore-2-770x260.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 0, 410, 80);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookStore/west-bookstore-2-770x260.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 320, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Statistical Information");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 30, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 760, 580);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void idListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idListMouseClicked
       
    }//GEN-LAST:event_idListMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String bid=(String)idList.getSelectedItem();
        int count=BookStore.getNumberOfCopiesLeft(bid);
        if(count>0)
            count=count-1;
        String query2="update book set copyleft='"+count+"' where isbn='"+bid+"'";
        
        BookStore.excuteUpdate(query2);
        this.setVisible(false);
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_submitMouseClicked

    private void idListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idListItemStateChanged
        String id=(String)idList.getSelectedItem();
        String title=BookStore.getTitleById(id);
        jLabel10.setText(title);
    }//GEN-LAST:event_idListItemStateChanged

    private void addBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookButtonMouseClicked
        BookEditor opt=new BookEditor();
        opt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        opt.setTitle("Options Window");
        this.setVisible(false);
        this.dispose();
        opt.setVisible(true);
    }//GEN-LAST:event_addBookButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> idList;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel result;
    private javax.swing.JButton submit;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
